In [1]:
X = rand(10, 4)

10×4 Array{Float64,2}:
 0.37286   0.676714   0.40126    0.80576 
 0.228578  0.339034   0.0242557  0.28646 
 0.480525  0.659057   0.491724   0.555683
 0.765848  0.367375   0.574516   0.197365
 0.569898  0.462095   0.127861   0.588978
 0.581349  0.118956   0.730928   0.737173
 0.143286  0.391312   0.39082    0.18062 
 0.858951  0.699152   0.910734   0.660157
 0.617428  0.0450365  0.425527   0.186302
 0.589401  0.6544     0.37336    0.512039

In [2]:
size(X)

(10, 4)

In [3]:
# first 3 rows
X[1:3, :]

3×4 Array{Float64,2}:
 0.37286   0.676714  0.40126    0.80576 
 0.228578  0.339034  0.0242557  0.28646 
 0.480525  0.659057  0.491724   0.555683

In [4]:
X[end-3:end, :]

4×4 Array{Float64,2}:
 0.143286  0.391312   0.39082   0.18062 
 0.858951  0.699152   0.910734  0.660157
 0.617428  0.0450365  0.425527  0.186302
 0.589401  0.6544     0.37336   0.512039

In [16]:
y = [1; 2; 1; 2; 1; 1; 2; 2; 2; 2]

10-element Array{Int64,1}:
 1
 2
 1
 2
 1
 1
 2
 2
 2
 2

In [17]:
length(y)

10

In [9]:
X

10×4 Array{Float64,2}:
 0.37286   0.676714   0.40126    0.80576 
 0.228578  0.339034   0.0242557  0.28646 
 0.480525  0.659057   0.491724   0.555683
 0.765848  0.367375   0.574516   0.197365
 0.569898  0.462095   0.127861   0.588978
 0.581349  0.118956   0.730928   0.737173
 0.143286  0.391312   0.39082    0.18062 
 0.858951  0.699152   0.910734   0.660157
 0.617428  0.0450365  0.425527   0.186302
 0.589401  0.6544     0.37336    0.512039

In [18]:
index_1 = (y .== 1)

10-element BitArray{1}:
 1
 0
 1
 0
 1
 1
 0
 0
 0
 0

In [11]:
index_1[1]

true

In [13]:
index_1[2]

false

In [20]:
X1 = X[index_1, :]

4×4 Array{Float64,2}:
 0.37286   0.676714  0.40126   0.80576 
 0.480525  0.659057  0.491724  0.555683
 0.569898  0.462095  0.127861  0.588978
 0.581349  0.118956  0.730928  0.737173

In [23]:
#μ_11: mean of first column
#μ_21: mean of second column
#μ_j1: mean of j-th column
#μ_1 = [μ_11, μ_21,...,μ_D1]

using Statistics
μ_1 = mean(X1, dims=1)


1×4 Array{Float64,2}:
 0.501158  0.479206  0.437943  0.671898

In [24]:
index_2 = (y .== 2)
X2 = X[index_2, :]
μ_2 = mean(X2, dims=1)

1×4 Array{Float64,2}:
 0.533915  0.416052  0.449869  0.337157

In [68]:
using DelimitedFiles

A_train = readdlm("iris.train")
A_test = readdlm("iris.test")

X_train = A_train[:,2:end]
y_train = Int.(A_train[:,1])

X_test = A_test[:, 2:end]
y_test = Int.(A_test[:, 1])


20×4 Array{Float64,2}:
 5.0  3.4  1.5  0.2
 4.6  3.6  1.0  0.2
 5.1  3.8  1.9  0.4
 4.9  3.0  1.4  0.2
 5.4  3.9  1.7  0.4
 4.4  3.2  1.3  0.2
 5.3  3.7  1.5  0.2
 6.1  2.9  4.7  1.4
 6.0  3.4  4.5  1.6
 5.5  2.3  4.0  1.3
 6.5  2.8  4.6  1.5
 6.8  2.8  4.8  1.4
 6.2  2.9  4.3  1.3
 6.7  3.0  5.2  2.3
 6.4  3.1  5.5  1.8
 5.7  2.5  5.0  2.0
 6.7  3.3  5.7  2.1
 6.8  3.2  5.9  2.3
 7.7  3.0  6.1  2.3
 7.3  2.9  6.3  1.8

In [52]:
function train(X::Array{Float64,2}, y::Array{Int})::Tuple{Array{Float64}, Array{Float64,2}, Array{Float64,2}}
    N, D = size(X)
    K = length(unique(y))
    μ = zeros(K, D)
    σ = zeros(K, D)
    θ = zeros(K)
    
    for k = 1:K
        index_k = y .== k
        θ[k] = sum(index_k)/N
        Xk = X[index_k, :]
        μ[k, :] = mean(Xk, dims=1)
        σ[k, :] = std(Xk, dims=1)
    end
    (θ, μ, σ)
end

train (generic function with 1 method)

In [56]:
θ, μ, σ = train(X_train, y_train)
println(θ)
println(μ)
println(σ)

[0.33076923076923076, 0.3384615384615385, 0.33076923076923076]
[5.013953488372093 3.40232558139535 1.4627906976744185 0.24186046511627904; 5.902272727272727 2.759090909090909 4.229545454545454 1.3136363636363637; 6.560465116279069 2.9697674418604647 5.532558139534883 2.016279069767442]
[0.35495230756018964 0.39004784327604836 0.15278876768419214 0.109615253847122; 0.5205045121282594 0.3112750834709582 0.4834851891406739 0.20413277609154643; 0.6388753268658623 0.33419048155557596 0.5664092959926881 0.28278397657688786]


In [61]:
function classify(x::Array{Float64}, θ, μ, σ)::Int
    K = length(θ)
    scores = zeros(K)
    for k = 1:K
        u = (x - μ[k, :]) .^ 2
        v = -log.(sqrt(2*pi) * σ[k,:]) - u ./ 2 ./ (σ[k, :] .^ 2)
        scores[k] = log(θ[k]) + sum(v)
    end
    argmax(scores)
end

classify (generic function with 1 method)

In [60]:
scores = rand(10)
println(scores)
argmax(scores)

[0.11002021400206319, 0.28534055636790523, 0.26265962949750965, 0.518371037359528, 0.5324643480098605, 0.2515635840959234, 0.31497247034186127, 0.7285356815756125, 0.8475018321379917, 0.8165974737265178]


9

In [80]:
function classify(X::Array{Float64,2}, θ, μ, σ)::Array{Int}
    N = size(X,1)
    y = zeros(N)
    for i=1:N
        y[i] = classify(X[i,:], θ, μ, σ)
    end
    y    
#    map(i -> classify(X[i,:], θ, μ, σ), collect(1:N))
end

classify (generic function with 2 methods)

In [81]:
prediction_test = classify(X_test, θ, μ, σ)

20-element Array{Int64,1}:
 1
 1
 1
 1
 1
 1
 1
 2
 2
 2
 2
 2
 2
 3
 3
 3
 3
 3
 3
 3

In [75]:
function evaluate(X::Array{Float64,2}, y::Array{Int}, θ, μ, σ)::Float64
    prediction = classify(X, θ, μ, σ)
    sum(prediction .== y)/length(y)
end

evaluate (generic function with 1 method)

In [77]:
test_accuracy = evaluate(X_test, y_test, θ, μ, σ)
train_accuracy = evaluate(X_train, y_train, θ, μ, σ)

0.9538461538461539